### ISSUE TITLE
Using swagger to create loopback models from remote loopback system

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-swagger#13]
I have a service running that uses loopback to provide rest apis. I wanted to use these apis in another, separate loopback system, so I thought I would be clever and use swagger as a round-trip between these 2 systems.

So system B used loopback-connector-swagger to connect to A, get the swagger spec and connect

```
let ds = loopback.createDataSource('swagger', {
                connector: 'loopback-connector-swagger',
                spec: `http://serverA/api/swagger.json`
            });

            ds.once('connected',() => {
                console.log("loaded");
                let Template = ds.createModel('Template',{});

                Template.find(,(err,response) => {
                    console.log("xxxxxxx",err,response)
                })
            });
```

however, it seems that the `err` variable seems to hold the response back from service A

```
xxxxxxx { url: 'http://serverA/api/templates',
  method: 'GET',
  headers: 
   { vary: 'Origin, Accept-Encoding',
     'access-control-allow-credentials': 'true',
     'access-control-allow-origin': '*',
     'content-type': 'application/json; charset=utf-8',
     etag: 'W/"19250-OMmKd4+pSmyj2qLOtLb0bA"',
     'content-encoding': 'gzip',
     date: 'Thu, 22 Sep 2016 13:42:10 GMT',
     connection: 'close',
     'transfer-encoding': 'chunked' },
  obj: 
   [ { name: 'botStudio',
```

it's also odd that the entire response seems to be passed as well , not just the result (ie the data)

Is this a problem with trying to talk to a remote loopback server ?

**Comment by gunjpan** [comment]
@jmls : Apologies for a delayed reply! 
Re: 
>it's also odd that the entire response seems to be passed as well , not just the result (ie the data)

I'm aware of the design issue here, for the inital release, we decided to go with the entire response and let dev. decide the information they need to send further. 

>however, it seems that the err variable seems to hold the response back from service A

I'll try to reproduce at earliest.
