### ISSUE TITLE
Why swagger Take two duplicate connectors.

### ISSUE THREAD

**Issue by Jeegen** [strongloop/loopback-connector-swagger#61]
hello,
	I have documentation on a swagger and I have some custom connectors. While I'm running that project in custom connectors a swagger takes two more connectors that are duplicate.

how to remove that. 

Thank You

**Comment by dhmlau** [comment]
@Jeegen, thank you for reporting the issue. Please provide the steps to reproduce the problem and a link to the reproduction sandbox, as explained in https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-3x-bugs. Thanks.
