### ISSUE TITLE
Why there is not option for Bearer token in security

### ISSUE THREAD

**Issue by Rehan712** [strongloop/loopback-connector-swagger#62]
Hi,
    I have a situation i need to pass bearer token through loopback-connector-swagger to other service. but it has only three options(apiKey,oAuth,basic auth). But there is not option for passing Bearer token.

I have loopback4 with docker image node:alpine

**Comment by raymondfeng** [comment]
Please use https://github.com/strongloop/loopback-connector-openapi instead.
