### ISSUE TITLE
Is there possibility of Pagination in Swagger.UI ?

### ISSUE THREAD

**Issue by Jeegen** [strongloop/loopback-connector-swagger#65]
Hello,
Is there any possibility of Pagination on Swagger.UI just because of reduce the Speed of loading controllers. I've 310 controllers so at a time load all the controllers so is there any way of pagination or scrolling down and load some controller.

**Comment by emonddr** [comment]
@deepakrkris , PTAL? thx.

**Comment by deepakrkris** [comment]
@Jeegen I guess this question is with reference to issues you face with https://github.com/strongloop/loopback-component-explorer . If so, https://swagger.io/tools/swagger-ui does not seem to have any docs on pagination. Also loopback-component-explorer is in maintenance phase. so we wouldn't be adding any new feature.
