### ISSUE TITLE
Error in README.md    installation instructions are wrong.

### ISSUE THREAD

**Issue by mercuriete** [strongloop/loopback-connector-swagger#7]
Actual README.md

In your application root directory, enter:

$ npm install loopback-connector-rest --save
This will install the module from npm and add it as a dependency to the application's package.json file.

It should be:

npm install loopback-connector-swagger --save

**Comment by gunjpan** [comment]
@mercuriete : Thanks for pointing it out. It has been corrected. Closing it now.
